#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UVapp.Resource", IsApplication=true)]

namespace UVapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int appExposureTimeText = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int bandConnectionText = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int bandExposureTimeText = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int connectbtn = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int currentUVText = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int currentlySamplingText = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int samplingIntervalText = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int skinColorText = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int timeYouCanSpendText = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int uvMinutesLeftText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int uvMinutesText = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Custom = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
